### PR TITLE
Respond to all of the events for a marker

### LINKED ISSUE #24: marker click action should send latlng
https://github.com/binhums/ember-cli-mapbox/blob/master/addon/components/mapbox-marker.js#L33
should be updated to send marker's latlng
```
marker.on('click', (e) => {
      this.sendAction('onclick', e.latlng);
    });
```
@binhums  if you want i can make PR

### PR DESCRIPTION
**Pull request by binhums**
Also provide the instance of the marker so we can get the position of the marker etc. Fixes #24.

Also adds tests to the repo :cake: 

A list of all marker events is available in the leaflet docs

  http://leafletjs.com/reference.html#marker-click

I wanted to set up some constants file so that we could do something like

```js
import { MARKER_EVENTS } from 'ember-cli-mapbox/constants/events'
```

but I couldn't get it working just yet.

### CODE REVIEW

**Comment by binhums** [comment]
@mileszim would you mind reviewing this for me? This should be a good starting point for your team if you are adding tests now.

**Comment by mileszim** [comment]
This looks great so far, thanks for starting the tests off!

**Comment by binhums** [comment]
Thanks @mileszim

**Comment by binhums** [comment]
Released https://github.com/binhums/ember-cli-mapbox/releases/tag/v0.3.2

**Pull request merged**
