### PR TITLE
Updating events

### PR DESCRIPTION
**Pull request by mileszim**

### CODE REVIEW

**Comment by mileszim** [comment]
whoops this was to the wrong place

**Comment by binhums** [comment]
Woaaaah! Awesome.

**Comment by binhums** [comment]
@mileszim are you going to reopen this PR?

**Comment by mileszim** [comment]
@binhums I have a lot of improvements/updates for this coming your way over the next week including this, so I'll open a PR when that's ready.

**Comment by binhums** [comment]
@mileszim sweet, when you do make sure you check out the comment on this issue

https://github.com/binhums/ember-cli-mapbox/issues/24#issuecomment-178197841

I think it would be good to start sending up the map / marker instance when we trigger the action.

**Comment by binhums** [comment]
@mileszim any updates here? If you want to pair up on it I'd be happy to.

**Pull request closed without merging**
