### PR TITLE
popupclose en popupopen added

### PR DESCRIPTION
**Pull request by WimAtIHomer**

### CODE REVIEW

**Comment by bdvholmes** [comment]
Fixes #17

**Comment by bdvholmes** [comment]
Excellent, can you add a README change and I'll get this deployed.

**Comment by WimAtIHomer** [comment]
onpopupopen and onpopupclose added to readme

**Comment by binhums** [comment]
Amazing. Thanks :+1:

**Comment by binhums** [comment]
Released [v0.2.5](https://github.com/binhums/ember-cli-mapbox/releases/tag/v0.2.5)

**Pull request merged**
